name = "kv"
type = "javascript"
zone_id = "4d1fa955d71d6b5e9eb19b2c3d098758"
route = ""
workers_dev = true
compatibility_date = "2022-04-22"
usage_model = "unbound"
kv_namespaces = [
  { binding = "DATABASE", id = "17718fa1a6ef445ebee17dbafedbc429" },
]

[build]
command = "npm run build:kv"

[build.upload]
format = "service-worker"

[vars]
CF_ACCOUNT_ID = "4d1fa955d71d6b5e9eb19b2c3d098758"

[env.preview]
workers_dev = true
kv_namespaces = [
  { binding = "DATABASE", id = "b520946288804ce284e309c493119542" },
]

[env.preview.vars]
KV_NAMESPACE_ID = "17718fa1a6ef445ebee17dbafedbc429"

[miniflare]
kv_persist = true
env_path = ".env.local"
