name: Check
on:
  push:
    branches:
      - alpha
      - beta
      - main
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          repository: LightDotSo/LightDotSo
      - uses: actions/checkout@v3
        with:
          path: apps/api
      - uses: ./.github/actions/pnpm
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - run: |
          pnpm run lint
      - if: failure()
        run: |
          pnpm run fix
      - if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v4
