name: Workers
on:
  push:
    branches:
      - alpha
      - beta
      - main
  pull_request:
jobs:
  workers:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        worker: ["cache", "image"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          repository: LightDotSo/LightDotSo
      - uses: actions/checkout@v3
        with:
          path: apps/api
      - uses: ./.github/actions/pnpm
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - run: |
          pnpx turbo run build --scope=@lightdotso/api --include-dependencies --no-deps || true
        env:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      - working-directory: apps/api
        run: |
          pnpm run build:${{ matrix.worker }}
      - working-directory: apps/api
        run: |
          mv wrangler.${{ matrix.worker }}.toml wrangler.toml
      - if: github.event_name == 'pull_request'
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: "preview"
          workingDirectory: apps/api
      - if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: apps/api
      - run: |
          sudo chown -R $USER:$USER ${{ github.workspace }}
          rm -rf .wrangler
      - uses: actions/checkout@v3
